'use strict'

export const REQUEST_EVENTS = "REQUEST_EVENTS"
export const RESPONSE_EVENTS = "RESPONSE_EVENTS"


export const REQUEST_EVENT = "REQUEST_EVENT"
export const RESPONSE_EVENT = "RESPONSE_EVENT"

export const REQUEST_LOCATIONS = "REQUEST_LOCATIONS"
export const RESPONSE_LOCATIONS = "RESPONSE_LOCATIONS"

export const CHANGE_CITY = "CHANGE_CITY"